-- AlterTable
ALTER TABLE `agendamentos` ADD COLUMN `status` ENUM('PENDENTE', 'REALIZADO', 'CANCELADO') NOT NULL DEFAULT 'PENDENTE';

-- AlterTable
ALTER TABLE `clientes` ADD COLUMN `tipo` ENUM('GRANDE_GERADOR', 'PEQUENO_GERADOR') NOT NULL DEFAULT 'PEQUENO_GERADOR';
